export const PROFESSION_OPTIONS = [
  "Account Manager",
  "Accountant",
  "Backend Engineer",
  "Business Analyst",
  "Content Writer",
  "Customer Support Specialist",
  "Data Analyst",
  "Data Engineer",
  "Data Scientist",
  "DevOps Engineer",
  "Executive Assistant",
  "Finance Manager",
  "Frontend Engineer",
  "Full-Stack Engineer",
  "Graphic Designer",
  "HR Manager",
  "HR Specialist",
  "Marketing Manager",
  "Marketing Specialist",
  "Mobile Developer (Android)",
  "Mobile Developer (iOS)",
  "Office Manager",
  "Operations Manager",
  "Paid Media Specialist",
  "Product Designer",
  "Product Manager",
  "Project Manager",
  "QA Engineer",
  "Recruiter",
  "Sales Manager",
  "Sales Representative",
  "SEO Specialist",
  "Site Reliability Engineer (SRE)",
  "Social Media Manager",
  "Software Engineer",
  "Solutions Architect",
  "Support Engineer",
  "System Administrator",
  "Technical Writer",
  "UX/UI Designer",
];

export const ARMENIAN_UNIVERSITIES = [
  "American University of Armenia (AUA)",
  "Armenian State University of Economics",
  "Artsakh State University",
  "Eurasia International University",
  "European Regional Educational Academy (EREA)",
  "French University in Armenia (UFAR)",
  "Gavar State University",
  "Goris State University",
  "International Scientific-Educational Center of NAS RA",
  "Khachatur Abovyan Armenian State Pedagogical University",
  "National Polytechnic University of Armenia",
  "National University of Architecture and Construction of Armenia",
  "Russian-Armenian (Slavonic) University",
  "Shirak State University",
  "TUMO Center for Creative Technologies",
  "Vanadzor State University",
  "Yerevan Brusov State University",
  "Yerevan State Medical University",
  "Yerevan State University (YSU)",
];

export type LocationOption = { value: string; label: string };

export const ARMENIAN_LOCATIONS: LocationOption[] = [
  { value: "Armenia", label: "Armenia" },
  { value: "Abovyan, Armenia", label: "Abovyan, Armenia" },
  { value: "Alaverdi, Armenia", label: "Alaverdi, Armenia" },
  { value: "Armavir, Armenia", label: "Armavir, Armenia" },
  { value: "Artashat, Armenia", label: "Artashat, Armenia" },
  { value: "Ashtarak, Armenia", label: "Ashtarak, Armenia" },
  { value: "Charentsavan, Armenia", label: "Charentsavan, Armenia" },
  { value: "Dilijan, Armenia", label: "Dilijan, Armenia" },
  { value: "Gavar, Armenia", label: "Gavar, Armenia" },
  { value: "Goris, Armenia", label: "Goris, Armenia" },
  { value: "Gyumri, Armenia", label: "Gyumri, Armenia" },
  { value: "Hrazdan, Armenia", label: "Hrazdan, Armenia" },
  { value: "Ijevan, Armenia", label: "Ijevan, Armenia" },
  { value: "Kapan, Armenia", label: "Kapan, Armenia" },
  { value: "Masis, Armenia", label: "Masis, Armenia" },
  { value: "Sevan, Armenia", label: "Sevan, Armenia" },
  { value: "Stepanavan, Armenia", label: "Stepanavan, Armenia" },
  { value: "Vagharshapat, Armenia", label: "Vagharshapat, Armenia" },
  { value: "Vanadzor, Armenia", label: "Vanadzor, Armenia" },
  { value: "Yerevan, Armenia", label: "Yerevan, Armenia" },
];

export const LANGUAGE_OPTIONS = [
  "Arabic",
  "Armenian",
  "Chinese",
  "English",
  "French",
  "Georgian",
  "German",
  "Italian",
  "Persian",
  "Russian",
  "Spanish",
  "Turkish",
];

export const LANGUAGE_LEVELS = ["A1", "A2", "B1", "B2", "C1", "C2", "Native"];

export const COMMON_SKILLS = [
  "Angular",
  "AWS",
  "C#",
  "C++",
  "CI/CD",
  "CSS",
  "Docker",
  "Django",
  "Figma",
  "Git",
  "Go",
  "GraphQL",
  "HTML",
  "Java",
  "JavaScript",
  "Kubernetes",
  "Linux",
  "MongoDB",
  "MySQL",
  "Next.js",
  "Node.js",
  "PHP",
  "PostgreSQL",
  "Python",
  "React",
  "Ruby",
  "Spring",
  "SQL",
  "TypeScript",
  "Vue",
];
