export const ARMENIAN_LOCATIONS = [
  "Armenia (remote, location doesn't matter)",
  "Yerevan, Armenia",
  "Gyumri, Armenia",
  "Vanadzor, Armenia",
  "Vagharshapat, Armenia",
  "Abovyan, Armenia",
  "Kapan, Armenia",
  "Hrazdan, Armenia",
  "Armavir, Armenia",
  "Gavar, Armenia",
  "Artashat, Armenia",
  "Ijevan, Armenia",
  "Sevan, Armenia",
  "Dilijan, Armenia",
  "Goris, Armenia",
  "Stepanavan, Armenia",
  "Alaverdi, Armenia",
  "Ashtarak, Armenia",
  "Charentsavan, Armenia",
  "Masis, Armenia",
];

export const LANGUAGE_OPTIONS = [
  "Armenian",
  "English",
  "Russian",
  "French",
  "German",
  "Spanish",
  "Italian",
  "Persian",
  "Arabic",
  "Georgian",
  "Chinese",
  "Turkish",
];

export const LANGUAGE_LEVELS = ["A1", "A2", "B1", "B2", "C1", "C2", "Native"];

export const COMMON_SKILLS = [
  "JavaScript",
  "TypeScript",
  "Python",
  "Go",
  "Java",
  "C#",
  "C++",
  "PHP",
  "Ruby",
  "React",
  "Next.js",
  "Vue",
  "Angular",
  "Node.js",
  "Django",
  "Spring",
  "PostgreSQL",
  "MySQL",
  "MongoDB",
  "AWS",
  "Docker",
  "Kubernetes",
  "Git",
  "Figma",
  "SQL",
  "HTML",
  "CSS",
  "GraphQL",
  "Linux",
  "CI/CD",
];
